<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Iridium.Extension</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Iridium\Iridium.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    </ItemGroup>

</Project>
