<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Models\Download\" />
      <Folder Include="Interfaces\Installation\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Flurl.Http" Version="4.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Iridium.SourceGenerators\Iridium.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
