using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Iridium.SourceGenerators;

/// <summary>
/// Generates AOT-friendly <c>ToResourceCategory()</c> extension methods for every
/// enum annotated with <c>[ResourceCategoryType]</c>, so the category enums can be
/// converted to <c>ResourceCategory</c> without runtime reflection.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ResourceCategoryGenerator : IIncrementalGenerator {
    private const string ResourceCategoryTypeAttribute = "Iridium.Resources.Attributes.ResourceCategoryTypeAttribute";
    private const string ModrinthCategoryAttribute = "Iridium.Resources.Attributes.ModrinthCategoryAttribute";
    private const string CurseForgeCategoryAttribute = "Iridium.Resources.Attributes.CurseForgeCategoryAttribute";
    private const string ResourceTypeEnum = "Iridium.Enums.ResourceType";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            ResourceCategoryTypeAttribute,
            static (node, _) => node is EnumDeclarationSyntax,
            static (ctx, _) => BuildModel(ctx));

        context.RegisterSourceOutput(models, static (spc, model) => {
            if (model is null)
                return;
            spc.AddSource($"{model.EnumName}.ResourceCategoryExtensions.g.cs",
                SourceText.From(model.Generate(), Encoding.UTF8));
        });
    }

    private static CategoryEnumModel? BuildModel(GeneratorAttributeSyntaxContext context) {
        if (context.TargetSymbol is not INamedTypeSymbol enumSymbol || enumSymbol.TypeKind != TypeKind.Enum)
            return null;

        var resourceType = ResolveResourceType(context, enumSymbol);
        if (resourceType is null)
            return null;

        var members = enumSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static field => field.HasConstantValue)
            .Select(field => new CategoryMemberModel(
                field.Name,
                GetAttributeString(field, ModrinthCategoryAttribute),
                GetAttributeInt(field, CurseForgeCategoryAttribute)))
            .ToArray();

        if (members.Length == 0)
            return null;

        return new CategoryEnumModel(
            enumSymbol.Name,
            enumSymbol.ContainingNamespace.ToDisplayString(),
            resourceType,
            members);
    }

    private static string? ResolveResourceType(GeneratorAttributeSyntaxContext context, INamedTypeSymbol enumSymbol) {
        var attribute = enumSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ResourceCategoryTypeAttribute);
        if (attribute?.ConstructorArguments is not { Length: > 0 } arguments)
            return null;

        var value = arguments[0].Value;
        return context.SemanticModel.Compilation.GetTypeByMetadataName(ResourceTypeEnum)?
            .GetMembers().OfType<IFieldSymbol>()
            .FirstOrDefault(member => member.HasConstantValue && Equals(member.ConstantValue, value))
            ?.Name;
    }

    private static string? GetAttributeString(ISymbol symbol, string attributeName) {
        var attribute = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == attributeName);
        return attribute?.ConstructorArguments.FirstOrDefault().Value as string;
    }

    private static int? GetAttributeInt(ISymbol symbol, string attributeName) {
        var attribute = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == attributeName);
        return attribute?.ConstructorArguments.FirstOrDefault().Value is int value ? value : null;
    }

    private sealed class CategoryEnumModel {
        public CategoryEnumModel(string enumName, string ns, string resourceType, CategoryMemberModel[] members) {
            EnumName = enumName;
            Namespace = ns;
            ResourceType = resourceType;
            Members = members;
        }

        public string EnumName { get; }
        public string Namespace { get; }
        public string ResourceType { get; }
        public CategoryMemberModel[] Members { get; }

        public string Generate() {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using Iridium.Enums;");
            builder.AppendLine("using Iridium.Resources.Models;");
            builder.AppendLine();
            builder.AppendLine($"namespace {Namespace};");
            builder.AppendLine();
            builder.AppendLine("public static partial class ResourceCategoryExtensions {");
            builder.AppendLine($"    public static ResourceCategory ToResourceCategory(this {EnumName} value) => value switch {{");
            foreach (var member in Members)
                builder.AppendLine($"        {EnumName}.{member.Name} => {member.BuildInitializer(ResourceType)},");
            builder.AppendLine("        _ => throw new global::System.ArgumentOutOfRangeException(nameof(value), value, null)");
            builder.AppendLine("    };");
            builder.AppendLine("}");
            return builder.ToString();
        }
    }

    private sealed class CategoryMemberModel {
        public CategoryMemberModel(string name, string? modrinthSlug, int? curseForgeId) {
            Name = name;
            ModrinthSlug = modrinthSlug;
            CurseForgeId = curseForgeId;
        }

        public string Name { get; }
        public string? ModrinthSlug { get; }
        public int? CurseForgeId { get; }

        public string BuildInitializer(string resourceType) {
            var name = ModrinthSlug ?? CurseForgeId?.ToString() ?? Name;
            var parts = new List<string> {
                $"Type = ResourceType.{resourceType}",
                $"Name = \"{name}\"",
                $"DisplayName = \"{Name}\""
            };
            if (CurseForgeId is { } id)
                parts.Add($"CurseForgeId = {id}");
            if (ModrinthSlug is { } slug)
                parts.Add($"ModrinthSlug = \"{slug}\"");
            return $"new ResourceCategory {{ {string.Join(", ", parts)} }}";
        }
    }
}
